package com.artgallery.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.artgallery.Author;
import com.artgallery.Work;

/**
 * Class _AuthorWorks was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AuthorWorks extends CayenneDataObject {

    public static final String AUTHOR_PROPERTY = "author";
    public static final String WORK_PROPERTY = "work";

    public static final String AUTHOR_WORKS_ID_PK_COLUMN = "author_works_id";

    public void setAuthor(Author author) {
        setToOneTarget("author", author, true);
    }

    public Author getAuthor() {
        return (Author)readProperty("author");
    }


    public void addToWork(Work obj) {
        addToManyTarget("work", obj, true);
    }
    public void removeFromWork(Work obj) {
        removeToManyTarget("work", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Work> getWork() {
        return (List<Work>)readProperty("work");
    }


}
