package com.artgallery.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.artgallery.Member;
import com.artgallery.Work;

/**
 * Class _Favoriates was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Favoriates extends CayenneDataObject {

    public static final String MEMBER_PROPERTY = "member";
    public static final String WORK_PROPERTY = "work";

    public static final String FAV_ID_PK_COLUMN = "fav_id";

    public void setMember(Member member) {
        setToOneTarget("member", member, true);
    }

    public Member getMember() {
        return (Member)readProperty("member");
    }


    public void addToWork(Work obj) {
        addToManyTarget("work", obj, true);
    }
    public void removeFromWork(Work obj) {
        removeToManyTarget("work", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Work> getWork() {
        return (List<Work>)readProperty("work");
    }


}
