package com.artgallery.auto;

import org.apache.cayenne.CayenneDataObject;

import com.artgallery.Author;
import com.artgallery.Favoriates;

/**
 * Class _Member was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Member extends CayenneDataObject {

    public static final String EMAIL_PROPERTY = "email";
    public static final String PASSWORD_PROPERTY = "password";
    public static final String AUTHOR_PROPERTY = "author";
    public static final String FAVORIATES_PROPERTY = "favoriates";

    public static final String MEMBER_ID_PK_COLUMN = "member_id";

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setPassword(String password) {
        writeProperty("password", password);
    }
    public String getPassword() {
        return (String)readProperty("password");
    }

    public void setAuthor(Author author) {
        setToOneTarget("author", author, true);
    }

    public Author getAuthor() {
        return (Author)readProperty("author");
    }


    public void setFavoriates(Favoriates favoriates) {
        setToOneTarget("favoriates", favoriates, true);
    }

    public Favoriates getFavoriates() {
        return (Favoriates)readProperty("favoriates");
    }


}
